# Javascript Node CircleCI 2.0 configuration file
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:12.15.0
    steps:
      - checkout
      - setup_remote_docker
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install dependencies
          command: yarn install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          name: Build the application
          command: yarn build
      - persist_to_workspace:
          root: ./
          paths:
            - build

  deploy:
    docker:
      - image: circleci/node:12.15.0
    steps:
      - setup_remote_docker
      - attach_workspace:
          at: ./
      - run:
          #Get all pre-requisites
          command: |
            apk add --no-cache \
              py-pip=9.0.0-r1
            pip install \
              awscli==1.14.37
            aws s3 sync build/ s3://com.michael.morgan --delete

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - feature/typescript-migration