version: 2 # use CircleCI 2.0
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/node:10
    steps:
      - checkout # special step to check out source code to working directory

      - restore_cache: # special step to restore the dependency cache
          # Read about caching dependencies: https://circleci.com/docs/2.0/caching/
          keys: 
            - v1-repo-{{ checksum "package.json" }}

      - run:
          name: Install Yarn Globaly
          command: npm i -g yarn

      - run:
          name: Install dependencies with YARN
          command: yarn install # replace with `yarn install` if using yarn

      - save_cache: # special step to save the dependency cache
          key: v1-repo-{{ checksum "package.json" }}
          paths:
            - "node_modules"

      - run:
          name: Run build
          # Runs jest with "--maxWorkers=2" argument to avoid OOM issues
          command: yran build # replace with `yarn test` if using yarn
  deploy:
    machine:
      enabled: true
    working_directory: ~/repo
    steps:
       - run:
          name: Deploy
          command: 'aws s3 sync ./build s3://com.michael.morgan --region us-west-2'

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: feature/typescript-migration # Only deploys when the commit is on the feature/typescript-migration branch