export const FETCH_CATALOG = 'FETCH_CATALOG';
export const FETCH_CATALOG_SUCCESS = 'FETCH_CATALOG_SUCCESS';
export const FETCH_CATALOG_FAIL = 'FETCH_CATALOG_FAIL';
export const SEARCH_BY_TEXT = 'SEARCH_BY_TEXT';

export const SELECT_ANNOUNCE_YEAR = 'SELECT_ANNOUNCE_YEAR';
export const SELECT_ANNOUNCE_MONTH = 'SELECT_ANNOUNCE_MONTH';
export const SELECT_BRAND = 'SELECT_BRAND';
export const SELECT_PRICE = 'SELECT_PRICE';
